apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
      version: blue
  template:
    metadata:
      labels:
        app: order
        version: blue
    spec:
      containers:
        - name: order
          image: iamalan10/order:latest 
          imagePullPolicy: Always  
          ports:
            - containerPort: 3003
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
