apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-green
spec:
  replicas: 0
  selector:
    matchLabels:
      app: order
      version: green
  template:
    metadata:
      labels:
        app: order
        version: green
    spec:
      containers:
        - name: order
          image: order-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3003
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
