apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
  type: LoadBalancer
