apiVersion: apps/v1
kind: Deployment
metadata:
  name: serv-green
spec:
  replicas: 0
  selector:
    matchLabels:
      app: serv
      version: green
  template:
    metadata:
      labels:
        app: serv
        version: green
    spec:
      containers:
        - name: serv
          image: serv-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
