apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product
    version: blue  # or green, depending on the version you want
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: ClusterIP
